name: adf_v1.0.1
channels:
  - conda-forge
  - defaults
dependencies:
  - pyyaml=6.0.3
  - scipy=1.18.0
  - cartopy=0.25.0
  - netcdf4=1.7.4
  - xarray=2026.7.0
  - uxarray=2026.07.0
  - matplotlib=3.10.9
  - pandas=3.0.5
  - pint=0.25.3
  - xskillscore=0.0.29
  - geocat-comp=2026.04.0
  - python=3.12
  - xesmf=0.9.2
